name: resep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/lg.png"
  min_sdk_android: 16 

flutter:
  uses-material-design: true

  assets:
    - images/lg.png
    - images/makanan_slide1.jpg
    - images/makanan_slide2.jpg
    - images/makanan_slide3.jpg
    - images/recommended1.jpg
    - images/recommended2.jpg
    - images/recommended3.jpg
    - images/recommended4.jpg
    - images/nasi_goreng.png
    - images/nasi_pecel.png
    - images/nasi_kuning.png
    - images/bubur_ayam.png
    - images/chicken_katsu.png
    - images/sayur_asem.png
    - images/rawon.png
    - images/ayam_geprek.png
    - images/es_buah.png
    - images/daifuku_mochi.png
    - images/lava_cake.png
    - images/lava_cake.png
    - images/puding_caramel.png
    - images/pisang_nuget.png
    - images/gyoza.png
    - images/donat_kentang.png
    - images/cilok.png
    - images/resep_nasi_goreng.png
    - images/resep_nasi_pecel.png
    - images/resep_bubur_ayam.png
    - images/resep_chicken_katsu.png
    - images/resep_ayam_geprek.png
    - images/resep_sayur_asem.png
    - images/resep_rawon.png
    - images/resep_es_buah.png
    - images/resep_daifuku_mochi.png
    - images/resep_choco_lava.png
    - images/resep_puding_caramel.png
    - images/resep_cilok.png
    - images/resep_donat_kentang.png
    - images/resep_gyoza.png
    - images/resep_pisang_nugget.png
