// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPfmHC48VoTsOrRrBt29d6ZaRWM8fBpE',
    appId: '1:728251412222:android:27a5757a1fefc4a8937faf',
    messagingSenderId: '728251412222',
    projectId: 'resep-30bc0',
    databaseURL: 'https://resep-30bc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resep-30bc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Xr47CHDoC5RstmgQTdpbuAMCDM1JWks',
    appId: '1:728251412222:ios:a001184983162f14937faf',
    messagingSenderId: '728251412222',
    projectId: 'resep-30bc0',
    databaseURL: 'https://resep-30bc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resep-30bc0.appspot.com',
    iosBundleId: 'com.example.resep',
  );
}
